development:
    adapter: postgresql
    database: development_seamosbuenaventura
    encoding: utf8
    username: root
    password:
    host: localhost
test: &test
    adapter: postgresql
    database: test_seamosbuenaventura
    encoding: utf8
    username: root
    password:
    host: localhost
production:
    adapter: postgresql
    database: production_seamosbuenaventura
    encoding: utf8
    username: root
    password:
    host: localhost