default: &default
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: development_seamosbuenaventura

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: test_seamosbuenaventura

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  database: production_seamosbuenaventura

staging:
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  database: staging_seamosbuenaventura