default: &default
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: development_seamos

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: test_seamos

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  database: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

staging:
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  database: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>